---
# This playbook assumes you already have the kubectl binary installed
# and available in the $PATH.
- hosts: all
  become: yes

  tasks:
    - name: Get the phpmyadmin Pod name.
      command: >
        kubectl get pods
        
    - name: Get the phpmyadmin Pod name.
      command: >
        kubectl get deployments
        
    - name: Get the phpmyadmin Pod name.
      command: >
        kubectl apply -f kubectl-deployment.yaml
