apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: java-app-1-deployment 
spec: 
  selector: 
    matchLabels: 
      app: java-app-1 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: java-app-1 
    spec: 
      containers: 
      - name: java-app-1 
        image: subratit/projects-mar-22-login-webapp:latest
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-app-1-service 
spec: 
  selector: 
    app: java-app-1 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31056
  type: NodePort 
